name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build-gateway:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get git commit
        id: get_git_commit
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          outputs: "type=image,push=false"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            VERSION=${{ env.TAG }}
            GIT_COMMIT=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/gateway:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/gateway:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER }}/gateway:latest

  build-auth-plugins:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19.x]
        svc: [
          basic-auth
        ]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get git commit
        id: get_git_commit
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git describe --tags --dirty)" >> $GITHUB_ENV
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Build ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./auth/${{ matrix.svc }}
          file: ./auth/${{ matrix.svc }}/Dockerfile
          outputs: "type=image,push=false"
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.svc }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.svc }}:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER }}/${{ matrix.svc }}:latest
